name: Node CI

on: [ push, pull_request ]

jobs:
  build:
    strategy:
      matrix:
        node-version: [ 18, 20 ]
        os: [ windows-latest, ubuntu-latest, macOS-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install

      - run: npm test
