name: Node CI

on: [ push, pull_request ]

jobs:
  build:
    strategy:
      matrix:
        node-version: [ 18, 20 ]
        os: [ windows-latest, ubuntu-latest, macOS-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm it
